Added a debug line
Prints progress because I am getting an odd KeyError with the dumpensemblgeneid function. Wondering if there is just simply no data (due to intronic region)

Error message
Traceback (most recent call last):
  File "C:\Users\Micha\Documents\KPU Research\Ataxia Project\Working Folder\VariantAnnotation.py", line 200, in <module>
    LIST_ANNO = va.combineanno(LIST_MVI, LIST_VEP)
  File "C:\Users\Micha\Documents\KPU Research\Ataxia Project\Working Folder\va.py", line 665, in combineanno
    'gene_id':dumpensemblgeneid(listvep[i])
  File "C:\Users\Micha\Documents\KPU Research\Ataxia Project\Working Folder\va.py", line 302, in dumpensemblgeneid
    while i < len(data['transcript_consequences']):
KeyError: 'transcript_consequences'